export const CardData = {
  general: [
    {
      id: 1,
      title: "About You",
      description: "Brief description...",
      slug: "about-you",
      category: "general_readings",
      type: "free",
    },
    {
      id: 2,
      title: "Primary Traits",
      description: "Brief description...",
      slug: "primary-traits",
      category: "general_readings",
      type: "free",
    },
    {
      id: 3,
      title: "Saptawara",
      description: "Brief description...",
      slug: "saptawara",
      category: "general_readings",
      type: "free",
    },
    {
      id: 4,
      title: "Pancawara",
      description: "Brief description...",
      slug: "pancawara",
      category: "general_readings",
      type: "free",
    },
    {
      id: 5,
      title: "Pancasuda",
      description: "Brief description...",
      slug: "pancasuda",
      category: "general_readings",
      type: "free",
    },
    {
      id: 6,
      title: "Laku",
      description: "Brief description...",
      slug: "laku",
      category: "general_readings",
      type: "free",
    },
    {
      id: 7,
      title: "Values",
      description: "Brief description...",
      slug: "values",
      category: "general_readings",
      type: "pro",
    },
    {
      id: 8,
      title: "Interaction Style",
      description: "Brief description...",
      slug: "interaction-style",
      category: "general_readings",
      type: "pro",
    },
    {
      id: 9,
      title: "General Life Path",
      description: "Brief description...",
      slug: "general-life-path",
      category: "general_readings",
      type: "pro",
    },
  ],
  love: [
    {
      id: 10,
      title: "Your Love",
      description: "Brief description...",
      slug: "your-love",
      category: "love_readings",
      type: "free",
    },
    {
      id: 11,
      title: "Love Style",
      description: "Brief description...",
      slug: "your-love",
      category: "love_readings",
      type: "free",
    },
    {
      id: 12,
      title: "Love Attitudes",
      description: "Brief description...",
      slug: "your-love",
      category: "love_readings",
      type: "free",
    },
    {
      id: 13,
      title: "Attachement Style",
      description: "Brief description...",
      slug: "your-love",
      category: "love_readings",
      type: "free",
    },
    {
      id: 14,
      title: "What You Can Offer",
      description: "Brief description...",
      slug: "your-love",
      category: "love_readings",
      type: "pro",
    },
    {
      id: 15,
      title: "Compatible With",
      description: "Brief description...",
      slug: "your-love",
      category: "love_readings",
      type: "pro",
    },
    {
      id: 16,
      title: "Uncompatible With",
      description: "Brief description...",
      slug: "your-love",
      category: "love_readings",
      type: "pro",
    },
  ],
  work: [
    {
      id: 17,
      title: "Your Career",
      description: "Brief description...",
      slug: "your-career",
      category: "work_readings",
      type: "pro",
    },
    {
      id: 18,
      title: "Ideal Life",
      description: "Brief description...",
      slug: "ideal-life",
      category: "work_readings",
      type: "pro",
    },
    {
      id: 19,
      title: "Key Life Events",
      description: "Brief description...",
      slug: "key-life-events",
      category: "work_readings",
      type: "pro",
    },
  ],
  financial: [
    {
      id: 20,
      title: "Your Financial",
      description: "Brief description...",
      slug: "your-financial",
      category: "financial_readings",
      type: "pro",
    },
  ],
};

export const SectionData = [
  {
    title: "General Readings",
    subtitle: "Understand more about yourself",
    cards: CardData.general,
  },
  {
    title: "Love and Relationship",
    subtitle: "Understand more about your personality in the love world",
    cards: CardData.love,
  },
  {
    title: "Work, Career, and Purpose",
    subtitle: "Help you find a carrer that suits you best",
    cards: CardData.work,
  },
  {
    title: "Financial Fortune",
    subtitle: "Help you manage your financials",
    cards: CardData.financial,
  },
];
